[package]
name    = "flora"
version = "0.1.0"
authors = ["Logan Bell <loganbell@gmail.com>"]

[lib]
name = "flora"
path = "src/lib.rs"

[dependencies]
base64 = "~0.5.0"
regex  = "0.1"
time   = "0.1"
uuid   = { version = "0.2", features = ["v4"] }
